name: "Build"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: "Build higherlower.c"
        run: "gcc higherlower.c -o higherlower.exe"